name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-petram:
    name: Build Petram
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-30-node
      options: --user 0:0
    steps:
      - uses: actions/checkout@v4

      # ---- FIX EOL Debian Buster APT sources (and stale Google Cloud SDK entry) ----
      - name: Patch APT sources for Debian Buster (EOL)
        run: |
          set -eux
          # Point to archive mirrors
          sed -i 's|deb.debian.org/debian|archive.debian.org/debian|g' /etc/apt/sources.list
          sed -i 's|security.debian.org/debian-security|archive.debian.org/debian-security|g' /etc/apt/sources.list || true
          # buster/updates no longer exists in archive; use just "buster"
          sed -i 's|buster/updates|buster|g' /etc/apt/sources.list || true
          # Some archive snapshots are past Valid-Until; disable the check
          echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until
          # Remove stale google-cloud-sdk list (or you can add its key instead)
          rm -f /etc/apt/sources.list.d/google-cloud-sdk.list || true
          apt-get update -y

      - name: Install curl
        run: apt-get install -y curl

      - name: Download secure files
        run: curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
        env:
          SECURE_FILES_DOWNLOAD_PATH: ./Development

      - name: Ensure Android SDK (API 33)
        run: |
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.2"

      - name: Build Petram
        run: make build-petram
